{
 "title": "Push Notifications",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Platform", "label": "Platform", "query": "android, apple" }
  ]
 },
 "panels": [
  {
   "title": "Total Notifications",
   "type": "singlestat",
   "description": "The amount of notifications sent through the proxy",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(service_notifications_total{platform=\"$Platform\"}) without(type)"
    }
   ]
  },
  {
   "title": "Push Notification Messages",
   "type": "singlestat",
   "description": "The percentage of messages sent through the proxy",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(service_notifications_total{platform=\"$Platform\", type=\"message\"}) /  sum(service_notifications_total{platform=\"$Platform\"})"
    }
   ]
  },
  {
   "title": "Push Clear Notification",
   "type": "singlestat",
   "description": "Total percentage of clear notifications sent through the push proxy",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(service_notifications_total{platform=\"$Platform\", type=\"clear\"}) /  sum(service_notifications_total{platform=\"$Platform\"})"
    }
   ]
  },
  {
   "title": "Push Badge Update Notifications",
   "type": "singlestat",
   "description": "Total percentage of badge update notifications sent through the push proxy",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(service_notifications_total{platform=\"$Platform\", type=\"update_badge\"}) /  sum(service_notifications_total{platform=\"$Platform\"})"
    }
   ]
  },
  {
   "title": "Push Notifications Sent",
   "type": "singlestat",
   "description": "Percentage successfully sent to the platform notification services",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(service_success_total{platform=\"$Platform\"}) / sum(service_notifications_total{platform=\"$Platform\"})"
    }
   ]
  },
  {
   "title": "Push Notifications Failures",
   "type": "singlestat",
   "description": "Percentage successfully sent to the platform notification services",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(service_failure_total{platform=\"$Platform\"}) / sum(service_notifications_total{platform=\"$Platform\"})"
    }
   ]
  },
  {
   "title": "Notifications Requests",
   "type": "graph",
   "description": "Notification requests per minute.\n\nThe amount of notifications queued to be sent to FCM for delivery.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "idelta(service_notifications_total{platform=\"$Platform\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Successful Notifications",
   "type": "graph",
   "description": "Successful Notification per minute.\n\nThe amount of notifications that were successfully sent to FCM for delivery.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "idelta(service_success_total{platform=\"$Platform\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Notification Failure Rate",
   "type": "graph",
   "description": "Rate of notification failures per minute\nTotal number of failed notifications / total number of notification attempts",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit", "label": "Rate" }
   ],
   "targets": [
    {
     "expr": "rate(service_failure_total{platform=\"$Platform\"}[1m]) / sum(rate(service_notifications_total{platform=\"$Platform\"}[1m])) by(instance, job, platform, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Notification Failures Reason",
   "type": "grafana-piechart-panel",
   "description": "Why did the push notification failed to send",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "service_failure_with_reason_total{platform=\"$Platform\"}",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Mean Request Time",
   "type": "graph",
   "description": "The time it took to process the request from the MM server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms", "label": "Milliseconds (ms)" }
   ],
   "targets": [
    {
     "expr": "1000.0 * rate(service_request_duration_seconds_sum[1m]) / rate(service_request_duration_seconds_count[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mean Notification Response Time",
   "type": "graph",
   "description": "The time it took to get the response from the Notification Service\n\nFCM for android\nAPNS for iOS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ms", "label": "Milliseconds (ms)" }
   ],
   "targets": [
    {
     "expr": "1000.0 * rate(service_notification_duration_seconds_sum{platform=\"$Platform\"}[1m]) / rate(service_notification_duration_seconds_count{platform=\"$Platform\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}