name: Enhancement request
description: 'For opening a enhancement request. '
title: '[Enhancement]:'
labels:
  - enhancement
body:
  - type: input
    attributes:
      label: What type of documentation is this?
      description: Guide/Troubleshooting etc
    validations:
      required: true
  - type: input
    attributes:
      label: Which page or section would this documentation live?
      description: Please provide a link
    validations:
      required: true
  - type: textarea
    attributes:
      label: Does this solve a problem or answer a question? Is it new content?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there a related thread or link to provide some context?
    validations:
      required: true
  - type: markdown
    attributes:
      value: >-
        ## Next steps:

        #### Once your PR is submitted, it will be reviewed by one of our
        #### technical writers. Additional reviewers, such as Product Managers and
        #### developers may also be included. We look forward to working with you!
