services:
  sphinx:
    build:
      context: ..
      dockerfile: typesense/Dockerfile
    command: bash -c "make livehtml & cd build/html && python -m http.server 8001"
    #  bash -c" cd ../.. && make livehtml"
    # volumes:
    #   - ".:/app"
    ports:
      # - "8000:8000"
      # - "8001:8001"
      - "8000:8001"

  typesense:
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=your_api_key
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_ENABLE_CORS=true
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data

  scraper:
    image: typesense/docsearch-scraper
    # profiles:
    #   - optional
    depends_on:
      - sphinx
    volumes:
      - ./config.json:/app/config.json
    network_mode: "host"
    environment:
      - CONFIG=/app/config.json
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_ENABLE_CORS=true
      # - TYPESENSE_API_KEY=your_api_key
      # - TYPESENSE_HOST=typesense
      # - TYPESENSE_PORT=8108
      # - TYPESENSE_PROTOCOL=http
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_HOST=${TYPESENSE_HOST}
      - TYPESENSE_PORT=443
      - TYPESENSE_PROTOCOL=https


volumes:
  typesense-data:
