services:
  typesense:
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=test_api_key
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_ENABLE_CORS=true
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data

  scraper:
    image: typesense/docsearch-scraper
    volumes:
      - ./config.json:/app/config.json
    network_mode: "host"
    environment:
      - CONFIG=/app/config.json
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_ENABLE_CORS=true
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY:-test_api_key}
      - TYPESENSE_HOST=${TYPESENSE_HOSTNAME:-localhost}
      - TYPESENSE_PORT=${TYPESENSE_PORT:-8108}
      - TYPESENSE_PROTOCOL=${TYPESENSE_PROTOCOL:-http}

volumes:
  typesense-data:
