# Mattermost documentation configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import sys
import os
from sphinx.application import Sphinx


def setup(_: Sphinx):
    return


# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath("../extensions"))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = "3.4.3"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autosectionlabel",
    "myst_parser",
    # `reredirects` is a local clone of sphinx_reredirects with parallel
    # read and write support enabled.
    # The original sphinx_reredirects extension can be found at:
    # https://documatt.gitlab.io/sphinx-reredirects/
    "reredirects",
    # `sitemap` is a local clone of sphinx_sitemap with parallel read
    # and write support enabled.
    # The original sphinx_sitemap extension can be found at:
    # https://pypi.org/project/sphinx-sitemap/
    "sitemap",
    "sphinx_tabs.tabs"
]

sphinx_tabs_disable_tab_closing = True
sphinx_tabs_disable_css_loading = False

# Prefix document path to section labels, otherwise autogenerated labels would look like 'heading'
# rather than 'path/to/file:heading'
autosectionlabel_prefix_document = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = [".rst", ".md"]

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# Redirects using: https://pypi.org/project/sphinx-reredirects/
redirects = {
    "integrations/jira": "https://mattermost.gitbook.io/plugin-jira/",
    "integrations/zoom": "https://mattermost.gitbook.io/plugin-zoom/",
    "integrations/net-promoter-score": "https://docs.mattermost.com/manage/user-satisfaction-surveys.html",
    "developer/interactive-dialogs": "https://developers.mattermost.com/integrate/admin-guide/admin-interactive-dialogs/",
    "developer/interactive-message-buttons": "https://developers.mattermost.com/integrate/admin-guide/admin-interactive-messages/",
    "developer/message-attachments": "https://developers.mattermost.com/integrate/admin-guide/admin-message-attachments/",
    "developer/oauth-2-0-applications": "https://developers.mattermost.com/integrate/admin-guide/admin-oauth2/",
    "developer/personal-access-token": "https://developers.mattermost.com/integrate/admin-guide/admin-personal-access-token/",
    "developer/slash-commands": "https://developers.mattermost.com/integrate/admin-guide/admin-slash-commands/",
    "developer/webhook-outgoing": "https://developers.mattermost.com/integrate/admin-guide/admin-webhooks-outgoing/",
    "developer/webhook-incoming": "https://developers.mattermost.com/integrate/admin-guide/admin-webhooks-incoming/",
    "developer/bot-accounts": "https://developers.mattermost.com/integrate/admin-guide/admin-bot-accounts/",
    "developer/localization": "https://handbook.mattermost.com/contributors/contributors/localization",
    "overview/product": "https://docs.mattermost.com/about/product.html",
    "overview/security": "https://docs.mattermost.com/about/security.html",
    "overview/integrations": "https://docs.mattermost.com/about/integrations.html",
    "overview/license-and-subscription": "https://docs.mattermost.com/about/licensing-and-subscription.html",
    "overview/auth": "https://docs.mattermost.com/about/corporate-directory-integration.html",
    "overview/compliance": "https://docs.mattermost.com/about/certifications-and-compliance.html",
    "overview/faq": "https://docs.mattermost.com/about/frequently-asked-questions.html",
    "overview/architecture": "https://docs.mattermost.com/getting-started/architecture-overview.html",
    "overview/license-and-subscription#frequently-asked-questions": 
        "https://docs.mattermost.com/about/licensing-and-subscription.html#frequently-asked-questions",
    "overview/product#mattermost-enterprise-edition-e10": 
        "https://docs.mattermost.com/about/product.html#mattermost-enterprise-edition-e10",
    "getting-started/implementation_plan": "https://docs.mattermost.com/getting-started/implementation-plan.html",
    "getting-started/welcome_email": "https://docs.mattermost.com/getting-started/welcome-email-to-end-users.html",
    "guides/orchestration": "https://docs.mattermost.com/about/orchestration.html",
    "guides/administrator": "https://docs.mattermost.com/guides/deployment.html",
    "guides/administrator": "https://docs.mattermost.com/guides/deployment.html",
    "guides/developer": "https://developers.mattermost.com/integrate/admin-guide/",
    "guides/integration": "https://developers.mattermost.com/integrate/getting-started/",
    "guides/user": "https://docs.mattermost.com/guides/channels.html",
    "guides/cloud-admin-guide": "https://docs.mattermost.com/guides/deployment.html",
    "install/requirements": "https://docs.mattermost.com/install/software-hardware-requirements.html",
    "install/install-ubuntu-2004": "https://docs.mattermost.com/install/installing-ubuntu-2004-LTS.html",
    "install/install-ubuntu-1804": "https://docs.mattermost.com/install/installing-ubuntu-1804-LTS.html",
    "install/mattermost-omnibus": "https://docs.mattermost.com/install/installing-mattermost-omnibus.html",
    "install/sockets-db": "https://docs.mattermost.com/install/setting-up-socket-based-mattermost-database.html",
    "install/ee-install": "https://docs.mattermost.com/install/enterprise-install-upgrade.html",
    "install/transport-encryption/config": "https://docs.mattermost.com/install/transport-encryption.html",
    "install/transport-encryption/config-mattermost":
        "https://docs.mattermost.com/install/proxy-to-mattermost-transport-encryption.html",
    "install/transport-encryption/config-database":
        "https://docs.mattermost.com/install/database-transport-encryption.html",
    "install/transport-encryption/config-cluster":
        "https://docs.mattermost.com/install/cluster-transport-encryption.html",
    "install/deploy-bitnami": "https://docs.mattermost.com/install/deploying-team-edition-on-bitnami.html",
    "install/docker-local-machine": "https://docs.mattermost.com/install/setting-up-local-machine-using-docker.html",
    "install/docker-ebs": "https://docs.mattermost.com/install/setting-up-aws-elastic-beanstalk-docker.html",
    "install/install-mmte-helm-gitlab-helm":
        "https://docs.mattermost.com/install/installing-team-edition-helm-chart.html",
    "install/desktop": "https://docs.mattermost.com/install/desktop-app-install.html",
    "install/desktop-managed-resources": "https://docs.mattermost.com/install/desktop-app-managed-resources.html",
    "install/desktop-msi-gpo":
        "https://docs.mattermost.com/install/desktop-msi-installer-and-group-policy-install.html",
    "install/smtp-email-setup": "https://docs.mattermost.com/configure/smtp-email.html",
    "install/config-cloudfront":
        "https://docs.mattermost.com/configure/configuring-cloudfront-to-host-mattermost-static-assets.html",
    "install/outbound-proxy": "https://docs.mattermost.com/configure/using-outbound-proxy.html",
    "install/i18n": "https://docs.mattermost.com/configure/enabling-chinese-japanese-korean-search.html",
    "install/config-apache2": "https://docs.mattermost.com/configure/configuring-apache2.html",
    "administration/telemetry": "https://docs.mattermost.com/manage/telemetry.html",
    "administration/changelog": "https://docs.mattermost.com/install/self-managed-changelog.html",
    "administration/command-line-tools": "https://docs.mattermost.com/manage/command-line-tools.html",
    "administration/compliance-export": "https://docs.mattermost.com/comply/compliance-export.html",
    "administration/config-settings#allow-users-to-view-archived-channels-beta":
        "https://docs.mattermost.com/configure/configuration-settings.html#allow-users-to-view-archived-channels-beta",
    "administration/config-settings#timezone": "https://docs.mattermost.com/configure/configuration-settings.html#timezone",
    "administration/config-settings#enable-legacy-sidebar":
        "https://docs.mattermost.com/configure/configuration-settings.html#enable-legacy-sidebar",
    "administration/config-settings#town-square-is-read-only-experimental":
        "https://docs.mattermost.com/configure/configuration-settings.html#town-square-is-read-only-experimental",
    "administration/config-settings#town-square-is-hidden-in-left-hand-sidebar-experimental":
        "https://docs.mattermost.com/configure/configuration-settings.html#town-square-is-hidden-in-left-hand-sidebar-experimental",
    "administration/config-settings#enable-x-to-leave-channels-from-left-hand-sidebar-experimental":
        "https://docs.mattermost.com/configure/configuration-settings.html#enable-x-to-leave-channels-from-left-hand-sidebar-experimental",
    "administration/config-settings#autoclose-direct-messages-in-sidebar-experimental":
        "https://docs.mattermost.com/configure/configuration-settings.html#autoclose-direct-messages-in-sidebar-experimental",
    "administration/config-settings#sidebar-organization":
        "https://docs.mattermost.com/configure/configuration-settings.html#sidebar-organization",
    "administration/config-settings#experimental-sidebar-features":
        "https://docs.mattermost.com/configure/configuration-settings.html#experimental-sidebar-features",
    "administration/config-settings#deprecated-configuration-settings":
        "https://docs.mattermost.com/configure/configuration-settings.html#deprecated-configuration-settings",
    "administration/custom-terms-of-service": "https://docs.mattermost.com/comply/custom-terms-of-service.html",
    "administration/image-proxy": "https://docs.mattermost.com/deploy/image-proxy.html",
    "administration/encryption": "https://docs.mattermost.com/deploy/encryption-options.html",
    "administration/extended-support-release": "https://docs.mattermost.com/upgrade/extended-support-release.html",
    "administration/backup": "https://docs.mattermost.com/deploy/backup-disaster-recovery.html",
    "administration/upgrade": "https://docs.mattermost.com/upgrade/upgrading-mattermost-server.html",
    "administration/important-upgrade-notes": "https://docs.mattermost.com/upgrade/important-upgrade-notes.html",
    "administration/version-archive": "https://docs.mattermost.com/upgrade/version-archive.html",
    "administration/extended-support-release": "https://docs.mattermost.com/upgrade/extended-support-release.html",
    "administration/release-lifecycle": "https://docs.mattermost.com/upgrade/release-lifecycle.html",
    "administration/downgrade": "https://docs.mattermost.com/upgrade/downgrading-mattermost-server.html",
    "administration/open-source-components": "https://docs.mattermost.com/upgrade/open-source-components.html",
    "administration/mmctl-cli-tool": "https://docs.mattermost.com/manage/mmctl-cli-tool.html",
    "administration/migrating#migrating-from-slack-using-the-mattermost-web-app":
        "https://docs.mattermost.com/onboard/migrating.html#migrating-from-slack-using-the-mattermost-web-app",
    "administration/migrating#migrating-from-slack-using-the-mattermost-mmetl-tool-and-bulk-import":
        "https://docs.mattermost.com/onboard/migrating.html#migrating-from-slack-using-the-mattermost-mmetl-tool-and-bulk-import",
    "administration/release-definitions": "https://docs.mattermost.com/upgrade/release-definitions.html",
    "administration/performance-alerting-guide": "https://docs.mattermost.com/scale/peformance-alerting.html",
    "administration/config-settings": "https://docs.mattermost.com/configure/configuration-settings.html",
    "administration/config-in-database":
        "https://docs.mattermost.com/configure/configuation-in-mattermost-database.html",
    "administration/branding": "https://docs.mattermost.com/configure/custom-branding-tools.html",
    "administration/config-settings#rate-limiting": 
        "https://docs.mattermost.com/configure/configuration-settings.html#rate-limiting",
    "administration/config-settings#customization": 
        "https://docs.mattermost.com/configure/configuration-settings.html#customization",
    "administration/config-settings#terms-of-service-link": 
        "https://docs.mattermost.com/configure/configuration-settings.html#terms-of-service-link",
    "administration/config-settings#ad-ldap": 
        "https://docs.mattermost.com/configure/configuration-settings.html#ad-ldap",
    "administration/config-settings#user-filter": 
        "https://docs.mattermost.com/configure/configuration-settings.html#user-filter",
    "administration/command-line-tools#mattermost-ldap-idmigrate": 
        "https://docs.mattermost.com/manage/command-line-tools.html#mattermost-ldap-idmigrate",
    "administration/config-settings#id-attribute": 
        "https://docs.mattermost.com/configure/configuration-settings.html#id-attribute",
    "administration/config-settings#login-id-attribute": 
        "https://docs.mattermost.com/configure/configuration-settings.html#login-id-attribute",
    "administration/config-settings#maximum-page-size": 
        "https://docs.mattermost.com/configure/configuration-settings.html#maximum-page-size",
    "administration/config-settings#enable-local-mode": 
        "https://docs.mattermost.com/configure/configuration-settings.html#enable-local-mode",
    "administration/config-settings#enable-local-mode-socket-location": 
        "https://docs.mattermost.com/configure/configuration-settings.html#enable-local-mode-socket-location",
    "administration/config-in-database#create-an-environment-file": 
        "https://docs.mattermost.com/configure/configuation-in-mattermost-database.html#create-an-environment-file",
    "administration/config-settings#enable-public-channel-creation-for": 
        "https://docs.mattermost.com/configure/configuration-settings.html#enable-public-channel-creation-for",
    "administration/config-settings#enable-public-channel-renaming-for": 
        "https://docs.mattermost.com/configure/configuration-settings.html#enable-public-channel-renaming-for",
    "administration/config-settings#data-retention-policy": 
        "https://docs.mattermost.com/configure/configuration-settings.html#data-retention-policy",
    "administration/command-line-tools.html#mattermost-channel-restore": 
        "https://docs.mattermost.com/manage/command-line-tools.html#mattermost-channel-restore",
    "administration/mmctl-cli-tool.html#mmctl-channel-modify": 
        "https://docs.mattermost.com/manage/command-line-tools.html#mattermost-channel-modify",
    "administration/config-settings#post-edit-time-limit": 
        "https://docs.mattermost.com/configure/configuration-settings.html#post-edit-time-limit",
    "administration/command-line-tools#mattermost-permissions-reset": 
        "https://docs.mattermost.com/manage/command-line-tools.html#mattermost-permissions-reset",
    "administration/command-line-tools#mattermost-permissions-export": 
        "https://docs.mattermost.com/manage/command-line-tools.html#mattermost-permissions-export",
    "administration/command-line-tools#mattermost-permissions-import": 
        "https://docs.mattermost.com/manage/command-line-tools.html#mattermost-permissions-import",
    "configure/configuration-settings#compliance-export-beta": 
        "https://docs.mattermost.com/configure/configuration-settings.html#compliance-export",
    "configure/configuration-settings#custom-terms-of-service-beta": 
        "https://docs.mattermost.com/configure/configuration-settings.html#custom-terms-of-service",
    "configure/configuration-settings#guest-access-beta": 
        "https://docs.mattermost.com/configure/configuration-settings.html#guest-access",
    "configure/configuration-settings#plugins-beta": 
        "https://docs.mattermost.com/configure/configuration-settings.html#plugins",
    "administration/upgrade#upgrade-team-edition-to-enterprise-edition": 
        "https://docs.mattermost.com/upgrade/upgrading-mattermost-server.html#upgrading-team-edition-to-enterprise-edition",
    "administration/migrating#migrating-from-slack-using-the-mattermost-mmetl-tool-and-bulk-import": 
        "https://docs.mattermost.com/onboard/migrating-to-mattermost.html#migrating-from-slack-using-the-mattermost-mmetl-tool-and-bulk-import",
    "administration/config-settings#enable-legacy-sidebar": 
        "https://docs.mattermost.com/configure/configuration-settings.html#enable-legacy-sidebar",
    "deployment/deployment": "https://docs.mattermost.com/deploy/deployment-overview.html",
    "deployment/advanced-permissions#read-only-channels": 
        "https://docs.mattermost.com/onboard/advanced-permissions.html#read-only-channels-e20",
    "deployment/bots": "https://developers.mattermost.com/integrate/admin-guide/admin-bot-accounts/",
    "deployment/on-boarding": "https://docs.mattermost.com/getting-started/admin-onboarding-tasks.html",
    "deployment/ha": "https://docs.mattermost.com/deployment/cluster.html",
    "deployment/webrtc": "https://docs.mattermost.com/deployment/video-and-audio-calling.html",
    "deployment/bleve": "https://docs.mattermost.com/deploy/bleve-search.html",
    "deployment/desktop-app-deployment": "https://docs.mattermost.com/deploy/desktop-app.html",
    "deployment/scaling": "https://docs.mattermost.com/scale/scaling-for-enterprise.html",
    "deployment/cluster": "https://docs.mattermost.com/scale/high-availability-cluster.html",
    "deployment/elasticsearch": "https://docs.mattermost.com/scale/elasticsearch.html",
    "deployment/metrics": "https://docs.mattermost.com/scale/performance-monitoring.html",
    "deployment/customize-mattermost": "https://docs.mattermost.com/configure/customizing-mattermost.html",
    "deployment/customize-email": "https://docs.mattermost.com/configure/email-templates.html",
    "deployment/advanced-permissions": "https://docs.mattermost.com/onboard/advanced-permissions.html",
    "deployment/permissions-backend":
        "https://docs.mattermost.com/onboard/advanced-permissions-backend-infrastructure.html",
    "deployment/admin-roles": "https://docs.mattermost.com/onboard/system-admin-roles.html",
    "deployment/guest-accounts": "https://docs.mattermost.com/onboard/guest-accounts.html",
    "deployment/sso-ldap": "https://docs.mattermost.com/onboard/ad-ldap.html",
    "deployment/auth": "https://docs.mattermost.com/onboard/multi-factor-authentication.html",
    "deployment/sso-openidconnect": "https://docs.mattermost.com/onboard/sso-openidconnect.html",
    "deployment/sso-gitlab": "https://docs.mattermost.com/onboard/sso-gitlab.html",
    "deployment/sso-google": "https://docs.mattermost.com/onboard/sso-google.html",
    "deployment/sso-office": "https://docs.mattermost.com/onboard/sso-office.html",
    "deployment/converting-oauth20-service-providers-to-openidconnect":
        "https://docs.mattermost.com/onboard/convert-oauth20-service-providers-to-openidconnect.html",
    "deployment/bulk-loading": "https://docs.mattermost.com/onboard/bulk-loading-data.html",
    "deployment/ldap-group-sync": "https://docs.mattermost.com/onboard/ad-ldap-groups-synchronization.html",
    "deployment/ldap-group-constrained-team-channel":
        "https://docs.mattermost.com/onboard/manage-team-channel-membership-using-ad-ldap-sync-groups.html",
    "deployment/sso-saml": "https://docs.mattermost.com/onboard/sso-saml.html",
    "deployment/sso-saml-okta": "https://docs.mattermost.com/onboard/sso-saml-okta.html",
    "deployment/sso-saml-technical": "https://docs.mattermost.com/onboard/sso-saml-technical.html",
    "deployment/sso-saml-adfs-msws2016": "https://docs.mattermost.com/onboard/sso-saml-adfs-msws2016.html",
    "deployment/ssl-client-certificate": "https://docs.mattermost.com/onboard/ssl-client-certificate.html",
    "deployment/team-channel-management": "https://docs.mattermost.com/manage/team-channel-members.html",
    "deployment/certificate-based-authentication":
        "https://docs.mattermost.com/onboard/certificate-based-authentication.html",
    "deployment/push": "https://docs.mattermost.com/deploy/mobile-hpns.html",
    "deployment/on-boarding#common-tasks": 
        "https://docs.mattermost.com/getting-started/admin-onboarding-tasks.html",
    "deployment/ldap-group-sync#add-default-teams-or-channels-for-the-group": 
        "https://docs.mattermost.com/onboard/ad-ldap-groups-synchronization.html#adding-default-teams-or-channels-for-the-group",
    "deployment/team-channel-management#profile": "https://docs.mattermost.com/manage/team-channel-members.html#profile",
    "administration/config-settings#files": "https://docs.mattermost.com/configure/configuration-settings.html#file-storage",
    "administration/config-settings#maximum-file-size":
        "https://docs.mattermost.com/configure/configuration-settings.html#maximum-file-size",
    "administration/config-settings#aggregate-search-indexes":
        "https://docs.mattermost.com/configure/configuration-settings.html#aggregate-search-indexes",
    "administration/changelog#database-changes-from-v3-4-to-v3-5":
        "https://docs.mattermost.com/install/self-managed-changelog.html#id41",
    "administration/config-settings#environment":
        "https://docs.mattermost.com/configure/configuration-settings.html#environment-variables",
    "administration/config-settings#site-configuration":
        "https://docs.mattermost.com/configure/configuration-settings.html#site-configuration",
    "administration/performance-alerting-guide": "https://docs.mattermost.com/scale/performance-monitoring.html",
    "administration/config-settings#policy": "https://docs.mattermost.com/configure/configuration-settings.html#policy",
    "administration/devops-command-center": "https://docs.mattermost.com/guides/incident-collaboration.html",
    "administration/plugins": "https://developers.mattermost.com/integrate/admin-guide/admin-plugins-beta/",
    "administration/migrating": "https://docs.mattermost.com/onboard/migrating-to-mattermost.html",
    "administration/user-provisioning": "https://docs.mattermost.com/onboard/user-provisioning-workflows.html",
    "administration/hipchat-migration-guidelines":
        "https://docs.mattermost.com/onboard/migrating-from-hipchat-to-mattermost.html",
    "administration/migration-announcement-email-template":
        "https://docs.mattermost.com/onboard/migration-announcement-email.html",
    "administration/generating-support-packet": "https://docs.mattermost.com/manage/generating-support-packet.html",
    "administration/mmctl-cli-tool": "https://docs.mattermost.com/manage/mmctl-command-line-tool.html",
    "administration/command-line-tools": "https://docs.mattermost.com/manage/command-line-tools.html",
    "administration/scripts": "https://docs.mattermost.com/manage/scripts.html",
    "administration/statistics": "https://docs.mattermost.com/manage/statistics.html",
    "administration/notices": "https://docs.mattermost.com/manage/in-product-notices.html",
    "administration/health-check": "https://docs.mattermost.com/manage/health-checks.html",
    "administration/announcement-banner": "https://docs.mattermost.com/manage/announcement-banner.html",
    "administration/bulk-export": "https://docs.mattermost.com/manage/bulk-export-tool.html",
    "administration/ediscovery": "https://docs.mattermost.com/comply/electronic-discovery.html",
    "administration/compliance": "https://docs.mattermost.com/comply/compliance-reporting-oversight.html",
    "administration/compliance-export": "https://docs.mattermost.com/comply/compliance-export.html",
    "administration/audit-log": "https://docs.mattermost.com/comply/audit-log.html",
    "administration/data-retention": "https://docs.mattermost.com/comply/data-retention-policy.html",
    "administration/custom-terms-of-service": "https://docs.mattermost.com/comply/custom-terms-of-service.html",
    "administration/mobile-changelog": "https://docs.mattermost.com/deploy/mobile-app-changelog.html",
    "administration/config-settings.html#allow-users-to-view-archived-channels-beta": 
        "https://docs.mattermost.com/administration/config-settings.html#allow-users-to-view-archived-channels",
    "administration/config-settings.html#push-notification-contents": "https://docs.mattermost.com/configure/configuration-settings.html#push-notification-contents",
    "administration/config-settings.html#gitlab-settings": "https://docs.mattermost.com/configure/configuration-settings.html#gitlab-settings",
    "administration/config-settings": "https://docs.mattermost.com/configure/configuration-settings.html",
    "administration/config-settings#push-notification-contents": 
        "https://docs.mattermost.com/configure/configuration-settings.html#push-notification-contents",
    "administration/config-settings#gitlab-settings":
        "https://docs.mattermost.com/configure/configuration-settings.html#gitlab-settings",
    "administration/config-settings#google-settings":
        "https://docs.mattermost.com/configure/configuration-settings.html#google-settings",
    "administration/config-settings#office-365-settings":
        "https://docs.mattermost.com/configure/configuration-settings.html#office-365-settings",
    "administration/config-settings#openid-connect-other-settings":
        "https://docs.mattermost.com/configure/configuration-settings.html#openid-connect-other-settings",
    "administration/config-settings#storage":
        "https://docs.mattermost.com/configure/configuration-settings.html#local-storage-directory",
    "administration/config-settings#aggregate-search-indexes":
        "https://docs.mattermost.com/configure/configuration-settings.html#aggregate-search-indexes",
    "administration/config-settings#enable-document-search-by-content":
        "https://docs.mattermost.com/configure/configuration-settings.html#enable-document-search-by-content",
    "administration/config-settings#site-url":
        "https://docs.mattermost.com/configure/configuration-settings.html#site-url",
    "administration/config-settings#enable-link-previews":
        "https://docs.mattermost.com/configure/configuration-settings.html#enable-link-previews",
    "administration/config-settings#enable-high-availability-mode":
        "https://docs.mattermost.com/configure/configuration-settings.html#enable-high-availability-mode",
    "administration/config-settings#forward-port-80-to-443":
        "https://docs.mattermost.com/configure/configuration-settings.html#forward-port-80-to-443",
    "administration/config-settings#smtp-email-server": 
        "https://docs.mattermost.com/configure/configuration-settings.html#smtp-email-server",
    "cloud/cloud-administration/cloud-changelog": "https://docs.mattermost.com/install/cloud-changelog.html",
    "cloud/cloud-administration/cloud-compliance":
        "https://docs.mattermost.com/comply/cloud-compliance-and-oversight.html",
    "cloud/cloud-administration/compliance-export": "https://docs.mattermost.com/comply/cloud-compliance-export.html",
    "cloud/cloud-administration/data-retention-policy":
        "https://docs.mattermost.com/comply/cloud-data-retention-policy.html",
    "cloud/cloud-administration/custom-terms-of-service":
        "https://docs.mattermost.com/comply/cloud-custom-terms-of-service.html",
    "cloud/cloud-billing/cloud-billing": "https://docs.mattermost.com/manage/cloud-billing.html",
    "cloud/cloud-administration/sso-saml": "https://docs.mattermost.com/onboard/cloud-sso-saml.html",
    "cloud/cloud-administration/saml-technical": "https://docs.mattermost.com/onboard/cloud-sso-saml-technical.html",
    "cloud/cloud-reporting": "https://docs.mattermost.com/manage/cloud-reporting.html",
    "cloud/cloud-administration/site-configuration":
        "https://docs.mattermost.com/configure/cloud-site-configuration.html",
    "cloud/cloud-mobile/cloud-app-config": "https://docs.mattermost.com/deploy/mobile-appconfig.html",
    "deployment/atlassian-integrations":
        "https://docs.mattermost.com/messaging/extending-messaging-with-integrations.html#atlassian-integrations",
    "deployment/bot-integrations":
        "https://docs.mattermost.com/messaging/extending-messaging-with-integrations.html#bot-integrations",
    "deployment/admin-roles": "https://docs.mattermost.com/deploy/admin-roles.html",
    "deployment/deployment": "https://docs.mattermost.com/deploy/deployment-overview.html",
    "deployment/bots": "https://developers.mattermost.com/integrate/admin-guide/admin-bot-accounts/",
    "deployment/guest-accounts": "https://docs.mattermost.com/deploy/guest-accounts.html",
    "deployment/on-boarding": "https://docs.mattermost.com/getting-started/admin-onboarding-tasks.html",
    "deployment/ha": "https://docs.mattermost.com/deployment/cluster.html",
    "deployment/webrtc": "https://docs.mattermost.com/deployment/video-and-audio-calling.html",
    "deployment/bleve": "https://docs.mattermost.com/deploy/bleve-search.html",
    "deployment/desktop-app-deployment": "https://docs.mattermost.com/deploy/desktop-app.html",
    "deployment/scaling": "https://docs.mattermost.com/scale/scaling-for-enterprise.html",
    "deployment/cluster": "https://docs.mattermost.com/scale/high-availability-cluster.html",
    "deployment/elasticsearch": "https://docs.mattermost.com/scale/elasticsearch.html",
    "deployment/metrics": "https://docs.mattermost.com/scale/performance-monitoring.html",
    "deployment/customize-mattermost": "https://docs.mattermost.com/configure/customizing-mattermost.html",
    "deployment/customize-email": "https://docs.mattermost.com/configure/email-templates.html",
    "deployment/advanced-permissions": "https://docs.mattermost.com/onboard/advanced-permissions.html",
    "deployment/permissions-backend":
        "https://docs.mattermost.com/onboard/advanced-permissions-backend-infrastructure.html",
    "deployment/admin-roles": "https://docs.mattermost.com/onboard/system-admin-roles.html",
    "deployment/guest-accounts": "https://docs.mattermost.com/onboard/guest-accounts.html",
    "deployment/sso-ldap": "https://docs.mattermost.com/onboard/ad-ldap.html",
    "deployment/auth": "https://docs.mattermost.com/onboard/multi-factor-authentication.html",
    "deployment/sso-openidconnect": "https://docs.mattermost.com/onboard/sso-openidconnect.html",
    "deployment/sso-gitlab": "https://docs.mattermost.com/onboard/sso-gitlab.html",
    "deployment/sso-google": "https://docs.mattermost.com/onboard/sso-google.html",
    "deployment/sso-office": "https://docs.mattermost.com/onboard/sso-office.html",
    "deployment/converting-oauth20-service-providers-to-openidconnect":
        "https://docs.mattermost.com/onboard/convert-oauth20-service-providers-to-openidconnect.html",
    "deployment/bulk-loading": "https://docs.mattermost.com/onboard/bulk-loading-data.html",
    "deployment/ldap-group-sync": "https://docs.mattermost.com/onboard/ad-ldap-groups-synchronization.html",
    "deployment/ldap-group-constrained-team-channel":
        "https://docs.mattermost.com/onboard/manage-team-channel-membership-using-ad-ldap-sync-groups.html",
    "deployment/sso-saml": "https://docs.mattermost.com/onboard/sso-saml.html",
    "deployment/sso-saml-okta": "https://docs.mattermost.com/onboard/sso-saml-okta.html",
    "deployment/sso-saml-technical": "https://docs.mattermost.com/onboard/sso-saml-technical.html",
    "deployment/sso-saml-adfs-msws2016": "https://docs.mattermost.com/onboard/sso-saml-adfs-msws2016.html",
    "deployment/ssl-client-certificate": "https://docs.mattermost.com/onboard/ssl-client-certificate.html",
    "deployment/team-channel-management": "https://docs.mattermost.com/manage/team-channel-members.html",
    "deployment/certificate-based-authentication":
        "https://docs.mattermost.com/onboard/certificate-based-authentication.html",
    "deployment/mobile-app-deployment": "https://docs.mattermost.com/deploy/mobile-overview.html",
    "deployment/deployment#file-store": "https://docs.mattermost.com/deploy/deployment-overview.html#file-store",
    "deployment/cluster#proxy-server-configuration": 
        "https://docs.mattermost.com/scale/high-availability-cluster.html#proxy-server-configuration",
    "deployment/cluster#upgrade-guide": "https://docs.mattermost.com/scale/high-availability-cluster.html#upgrade-guide",
    "deployment/mobile-app-deployment": "https://docs.mattermost.com/deploy/mobile-overview.html",
    "deployment/push.html": "https://docs.mattermost.com/deploy/mobile-hpns.html#mobile-push-notifications",
    "developer/localization": "https://handbook.mattermost.com/contributors/contributors/localization",
    "getting-started/implementation_plan": "https://docs.mattermost.com/getting-started/implementation-plan.html",
    "getting-started/welcome_email": "https://docs.mattermost.com/getting-started/welcome-email-to-end-users.html",
    "guides/orchestration": "https://docs.mattermost.com/about/orchestration.html",
    "guides/administrator": "https://docs.mattermost.com/guides/install-deploy-upgrade-scale.html",
    "guides/administrator": "https://docs.mattermost.com/guides/install-deploy-upgrade-scale.html",
    "guides/developer": "https://developers.mattermost.com/integrate/admin-guide/",
    "guides/integration": "https://developers.mattermost.com/integrate/getting-started/",
    "guides/user": "https://docs.mattermost.com/guides/channels.html",
    "guides/cloud-admin-guide": "https://docs.mattermost.com/guides/install-deploy-upgrade-scale.html",
    "guides/administrator#mattermost-integrations": "https://developers.mattermost.com/integrate/getting-started/",
    "guides/integration": "https://developers.mattermost.com/integrate/other-integrations/",
    "guides/install-deploy-upgrade-scale.html#install-mattermost":
        "https://docs.mattermost.com/guides/deployment.html#install-guides",
    "help/apps/desktop-changelog": "https://docs.mattermost.com/install/desktop-app-changelog.html",
    "help/getting-started/welcome-to-mattermost":
        "https://docs.mattermost.com/messaging/welcome-to-mattermost-messaging.html",
    "help/getting-started/access-your-workspace": "https://docs.mattermost.com/messaging/accessing-your-workspace.html",
    "help/getting-started/signing-in": "https://docs.mattermost.com/messaging/signing-in.html",
    "help/getting-started/switch-between-teams": "https://docs.mattermost.com/messaging/switching-between-teams.html",
    "help/getting-started/about-teams-channels-messages":
        "https://docs.mattermost.com/messaging/about-teams-channels-messages.html",
    "help/getting-started/log-out": "https://docs.mattermost.com/messaging/logging-out.html",
    "help/getting-started/searching": "https://docs.mattermost.com/messaging/searching-in-mattermost.html",
    "help/getting-started/creating-teams": "https://docs.mattermost.com/messaging/creating-teams.html",
    "help/settings/team-settings": "https://docs.mattermost.com/messaging/team-settings.html",
    "help/getting-started/organizing-conversations": "https://docs.mattermost.com/messaging/managing-channels.html",
    "help/getting-started/organizing": "https://docs.mattermost.com/messaging/organizing-mattermost.html",
    "help/settings/channel-settings": "https://docs.mattermost.com/messaging/channel-settings.html",
    "help/getting-started/managing-members": "https://docs.mattermost.com/messaging/managing-members.html",
    "help/getting-started/setting-your-status-availability":
        "https://docs.mattermost.com/messaging/setting-your-status-availability.html",
    "help/getting-started/configuring-notifications":
        "https://docs.mattermost.com/messaging/configuring-notifications.html",
    "help/getting-started/organizing-your-sidebar":
        "https://docs.mattermost.com/messaging/organizing-your-sidebar.html",
    "help/messaging/sending-messages": "https://docs.mattermost.com/messaging/sending-receiving-messages.html",
    "help/messaging/organizing-conversations": "https://docs.mattermost.com/messaging/organizing-conversations.html",
    "help/messaging/organizing-conversations#known-issues":
        "https://docs.mattermost.com/messaging/organizing-conversations.html#known-issues",
    "help/messaging/formatting-text": "https://docs.mattermost.com/messaging/formatting-text.html",
    "help/messaging/emoji": "https://docs.mattermost.com/messaging/using-emoji.html",
    "help/messaging/mentioning-teammates": "https://docs.mattermost.com/messaging/mentioning-teammates.html",
    "help/messaging/attaching-files": "https://docs.mattermost.com/messaging/sharing-files.html",
    "help/messaging/executing-commands": "https://docs.mattermost.com/messaging/executing-slash-commands.html",
    "help/messaging/flagging-messages": "https://docs.mattermost.com/messaging/saving-messages.html",
    "help/messaging/pinning-messages": "https://docs.mattermost.com/messaging/pinning-messages.html",
    "help/messaging/keyboard-shortcuts": "https://docs.mattermost.com/messaging/keyboard-shortcuts.html",
    "help/settings/custom-emoji": "https://docs.mattermost.com/messaging/using-custom-emoji.html",
    "help/settings/account-settings": "https://docs.mattermost.com/messaging/managing-account-settings.html",
    "help/settings/theme-colors": "https://docs.mattermost.com/messaging/customizing-theme-colors.html",
    "help/settings/desktop-app-options": "https://docs.mattermost.com/messaging/managing-desktop-app-options.html",
    "help/settings/manage-servers": "https://docs.mattermost.com/messaging/managing-desktop-app-servers.html",
    "help/getting-started/accessibility": "https://docs.mattermost.com/messaging/keyboard-accessibility.html",
    "help/settings/integration-settings":
        "https://docs.mattermost.com/messaging/extending-messaging-with-integrations.html",
    "help/getting-started/install-desktop-app":
        "https://docs.mattermost.com/install/installing-mattermost-desktop-app.html",
    "help/getting-started/light-install": "https://docs.mattermost.com/getting-started/light-install.html",
    "incident-collaboration/playbook-planning": 
        "https://docs.mattermost.com/incident-collaboration/setting-up-playbooks.html",
    "help/settings/custom-emoji": "https://docs.mattermost.com/messaging/using-emoji.html#creating-custom-emojis",
    "incident-collaboration/launching-playbooks": 
        "https://docs.mattermost.com/incident-collaboration/running-playbooks.html",
    "incident-collaboration/playbook-planning":
        "https://docs.mattermost.com/incident-collaboration/setting-up-playbooks.html",
    "incident-collaboration/launching-playbooks":
        "https://docs.mattermost.com/incident-collaboration/running-playbooks.html",
    "incident-collaboration/review-and-refine":
        "https://docs.mattermost.com/incident-collaboration/refining-and-improving.html",
    "incident-collaboration/overview": "https://docs.mattermost.com/playbooks/refining-and-improving.html",
    "incident-collaboration/getting-started": "https://docs.mattermost.com/playbooks/getting-started.html",
    "incident-collaboration/setting-up-playbooks": "https://docs.mattermost.com/playbooks/setting-up-playbooks.html",
    "incident-collaboration/running-playbooks": "https://docs.mattermost.com/playbooks/running-playbooks.html",
    "incident-collaboration/refining-and-improving": 
         "https://docs.mattermost.com/playbooks/refining-and-improving.html",
    "messaging/welcome-to-mattermost-messaging": 
        "https://docs.mattermost.com/messaging/welcome-to-mattermost-channels.html",
    "messaging/messaging-basics": "https://docs.mattermost.com/messaging/channels-basics.html",
    "messaging/organizing-mattermost": "https://docs.mattermost.com/messaging/organizing-channels.html",
    "messaging/channel-settings": "https://docs.mattermost.com/messaging/channel-settings.html#channel-header",
    "messaging/extending-messaging-with-integrations": 
        "https://docs.mattermost.com/messaging/extending-channels-with-integrations.html",
    "incident-collaboration/refining-and-improving":
         "https://docs.mattermost.com/playbooks/refining-and-improving.html",
    "install/requirements": "https://docs.mattermost.com/install/software-hardware-requirements.html",
    "install/install-ubuntu-2004": "https://docs.mattermost.com/install/installing-ubuntu-2004-LTS.html",
    "install/install-ubuntu-1804": "https://docs.mattermost.com/install/installing-ubuntu-1804-LTS.html",
    "install/mattermost-omnibus": "https://docs.mattermost.com/install/installing-mattermost-omnibus.html",
    "install/sockets-db": "https://docs.mattermost.com/install/setting-up-socket-based-mattermost-database.html",
    "install/ee-install": "https://docs.mattermost.com/install/enterprise-install-upgrade.html",
    "install/transport-encryption/config": "https://docs.mattermost.com/install/transport-encryption.html",
    "install/transport-encryption/config-mattermost":
        "https://docs.mattermost.com/install/proxy-to-mattermost-transport-encryption.html",
    "install/transport-encryption/config-database":
        "https://docs.mattermost.com/install/database-transport-encryption.html",
    "install/transport-encryption/config-cluster":
        "https://docs.mattermost.com/install/cluster-transport-encryption.html",
    "install/deploy-bitnami": "https://docs.mattermost.com/install/deploying-team-edition-on-bitnami.html",
    "install/docker-local-machine": "https://docs.mattermost.com/install/setting-up-local-machine-using-docker.html",
    "install/docker-ebs": "https://docs.mattermost.com/install/setting-up-aws-elastic-beanstalk-docker.html",
    "install/install-mmte-helm-gitlab-helm":
        "https://docs.mattermost.com/install/installing-team-edition-helm-chart.html",
    "install/desktop": "https://docs.mattermost.com/install/desktop-app-install.html",
    "install/desktop-managed-resources": "https://docs.mattermost.com/install/desktop-app-managed-resources.html",
    "install/desktop-msi-gpo":
        "https://docs.mattermost.com/install/desktop-msi-installer-and-group-policy-install.html",
    "install/smtp-email-setup": "https://docs.mattermost.com/configure/smtp-email.html",
    "install/config-cloudfront":
        "https://docs.mattermost.com/configure/configuring-cloudfront-to-host-mattermost-static-assets.html",
    "install/outbound-proxy": "https://docs.mattermost.com/configure/using-outbound-proxy.html",
    "install/i18n": "https://docs.mattermost.com/configure/enabling-chinese-japanese-korean-search.html",
    "install/config-apache2": "https://docs.mattermost.com/configure/configuring-apache2.html",
    "integrations/jira": "https://mattermost.gitbook.io/plugin-jira/",
    "integrations/zoom": "https://mattermost.gitbook.io/plugin-zoom/",
    "integrations/net-promoter-score": "https://docs.mattermost.com/manage/user-satisfaction-surveys.html",
    "mobile/mobile-overview#use-an-emm-provider-with-managed-app-configuration":
        "https://docs.mattermost.com/deploy/deploy-mobile-apps-using-emm-provider.html",
    "mobile/mobile-hpns": "https://docs.mattermost.com/deploy/mobile-hpns.html",
    "mobile/mobile-faq.html#how-do-push-notifications-work":
        "https://docs.mattermost.com/deploy/mobile-faq.html#how-do-push-notifications-work",
    "mobile/mobile-testing-notifications": "https://docs.mattermost.com/deploy/mobile-testing-notifications.html",
    "onboard/ad-ldap#active-directory-ldap-setup-e10-e20": 
        "https://docs.mattermost.com/onboard/ad-ldap.html#active-directory-ldap-setup",
    "overview/product": "https://docs.mattermost.com/about/product.html",
    "overview/security": "https://docs.mattermost.com/about/security.html",
    "overview/integrations": "https://docs.mattermost.com/about/integrations.html",
    "overview/license-and-subscription": "https://docs.mattermost.com/about/licensing-and-subscription.html",
    "overview/auth": "https://docs.mattermost.com/about/corporate-directory-integration.html",
    "overview/compliance": "https://docs.mattermost.com/about/certifications-and-compliance.html",
    "overview/faq": "https://docs.mattermost.com/about/frequently-asked-questions.html",
    "overview/architecture": "https://docs.mattermost.com/getting-started/architecture-overview.html",
    "overview/architecture#database-with-vips":
        "https://docs.mattermost.com/getting-started/architecture-overview.html#database-with-vips",
    "overview/architecture#reference-architectures":
        "https://docs.mattermost.com/getting-started/architecture-overview.html#reference-architectures",
    "process/help-wanted": "https://handbook.mattermost.com/contributors/contributors/help-wanted",
    "process/help-wanted": "https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/help-wanted",
    "process/sg_rest_markup":
        "https://handbook.mattermost.com/operations/operations/company-processes/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines/documentation-style-guide#document-structure",
    "process/security-release":
        "https://handbook.mattermost.com/operations/research-and-development/product/release-process/security-release",
    "process/community-overview": "https://handbook.mattermost.com/contributors/contributors/community",
    "process/handbook": "https://handbook.mattermost.com/company/about-mattermost",
    "process/release-faq":
        "https://handbook.mattermost.com/operations/research-and-development/product/release-process/release-overview",
    "process/release-tips":
        "https://handbook.mattermost.com/operations/research-and-development/product/release-process/release-tips",
    "process/sg_general-guidelines":
        "https://handbook.mattermost.com/operations/operations/company-processes/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines/documentation-style-guide#document-structure",
    "process/community-guidelines":
        "https://handbook.mattermost.com/contributors/contributors/community-playbook/",
    "process/feature-release":
        "https://handbook.mattermost.com/operations/research-and-development/product/release-process/feature-release",
    "process/security": "https://handbook.mattermost.com/operations/operations/company-policies/security-policies",
    "process/engineer-expectations":
        "https://handbook.mattermost.com/operations/workplace/people/working-at-mattermost/onboarding/engineer-onboarding",
    "process/product-manager-hiring":
        "https://handbook.mattermost.com/contributors/join-us/recruiting-cadences/product-manager-hiring",
    "process/new-bug-tickets":
        "https://handbook.mattermost.com/operations/research-and-development/product/development-process/new-bug-tickets",
    "process/sg_grammar-spelling-mechanics":
        "https://handbook.mattermost.com/operations/operations/company-processes/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines/documentation-style-guide#document-structure",
    "process/sg_document-structure":
        "https://handbook.mattermost.com/operations/operations/company-processes/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines/documentation-style-guide#document-structure",
    "process/release-scorecard-definitions":
        "https://handbook.mattermost.com/operations/research-and-development/product/release-process/release-scorecard-definitions",
    "process/software-requirements":
        "https://handbook.mattermost.com/operations/research-and-development/product/development-process/software-requirements",
    "process/mobile-release-process":
        "https://handbook.mattermost.com/operations/research-and-development/product/release-process/mobile-release",
    "process/documentation-UItext-guidelines":
        "https://handbook.mattermost.com/operations/research-and-development/product/development-process/user-interface-text-guidelines",
    "process/bug-fix-release":
        "https://handbook.mattermost.com/operations/research-and-development/product/release-process/bug-fix-release",
    "process/deprecated-features":
        "https://handbook.mattermost.com/operations/research-and-development/product/development-process/deprecated-features",
    "process/dot-release":
        "https://handbook.mattermost.com/operations/research-and-development/product/release-process/dot-release",
    "process/end-user-documentation":
        "https://handbook.mattermost.com/operations/operations/company-processes/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines/documentation-style-guide#document-structure",
    "process/bug-severity-guidelines":
        "https://handbook.mattermost.com/operations/research-and-development/product/development-process/new-bug-tickets/bug-severity-guidelines",
    "process/accepting-pull-request":
        "https://handbook.mattermost.com/contributors/contributors/help-wanted",
    "process/pm-faq":
        "https://handbook.mattermost.com/operations/research-and-development/product/product-management-team-handbook#frequently-asked-questions-faq",
    "process/product-manager":
        "https://handbook.mattermost.com/contributors/join-us/staff-recruiting/product-manager-hiring",
    "process/partner-programs":
        "https://handbook.mattermost.com/operations/sales/partner-programs",
    "process/overview":
        "https://handbook.mattermost.com/operations/research-and-development/product/development-process",
    "mobile/mobile-hpns": "https://docs.mattermost.com/deploy/mobile-hpns.html",
    "guides/install-deploy-upgrade-scale": "https://docs.mattermost.com/guides/deployment.html",
    "guides/setup-onboard-manage-comply.html": "https://docs.mattermost.com/guides/administration.html",
    "messaging/welcome-to-mattermost-messaging.html": "https://docs.mattermost.com/overview/index.html",
    "messaging/accessing-your-workspace.html": "https://docs.mattermost.com/messaging/signing-in.html",
    "guides/messaging": "https://docs.mattermost.com/guides/channels.html",
    "focalboard/installing-boards": "https://docs.mattermost.com/guides/boards.html",
    "configure/configuring-apache2.html": "https://forum.mattermost.org/c/docs/37"
}

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "Mattermost"
copyright = "2015-2021 Mattermost"
author = "Mattermost"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
# version = '6.0'
# The full version, including alpha/beta/rc tags.
# release = '6.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["archive/*"]

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

html_baseurl = "https://docs.mattermost.com/"

# Global variables available to all templates
html_context = {
    # Enable google analytics
    "googleanalytics_id": "UA-67846571-2",
    "googleanalytics_enabled": True,
    # Enable the "Edit in GitHub link within the header of each page.
    "display_github": True,
    # Set the following variables to generate the resulting github URL for each page. Format Template:
    # https://{{github_host|default("github.com") }}/{{ github_user }}/{{ github_repo }}/blob/{{ github_version }}{{conf_py_path }}{{ pagename }}{{ suffix }}
    "github_user": "mattermost",
    "github_repo": "docs",
    "github_version": "master/source/",
}

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    "collapse_navigation": False,
    "sticky_navigation": True,
    "navigation_depth": 4,
    "includehidden": True,
    "titles_only": False,
}

html_permalinks_icon = " "

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# A list of CSS files. The entry must be a filename string or a tuple containing the filename string and the attributes
# dictionary. The filename must be relative to the html_static_path, or a full URI with scheme like
# https://example.org/style.css. The attributes is used for attributes of <link> tag. It defaults to an empty list.
html_css_files = ["mytheme.css"]

# A list of JavaScript filenames. The entry must be a filename string or a tuple containing the filename string and the
# attributes dictionary. The filename must be relative to the html_static_path, or a full URI with scheme like
# https://example.org/script.js. The attributes is used for attributes of <script> tag. It defaults to an empty list.
html_js_files = ["myscript.js"]

# The name of an image file, relative to the configuration directory, to use as favicon of the docs.  This file should
# be a Windows icon file (.ico) being 16x16 or 32x32 pixels in size.
html_favicon = "_static/favicon.ico"

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
html_extra_path = ["_static/robots.txt"]

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
html_additional_pages = {
    'index': 'index.html',
    '404': '404.html'
}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
html_use_index = False

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'
# html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
# html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
# html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = "Mattermostdoc"
