name: CI
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ci/Checkout code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - uses: actions/setup-python@db9987b4c1f10f0404fa60ee629f675fafbd6763 # v4.6.0
      with:
        python-version: '3.9'
    - name: ci/Build
      run: |
        make python-deps
        make html
    - name: ci/Persist docs artifacts
      uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05 # v3.1.2
      with:
        name: docs
        path: build/html
    - name: ci/Persist doc logs artifacts
      uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05 # v3.1.2
      with:
        name: doc-logs
        path: build/*.log
