---
name: CI
'on':
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ci/Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.1
        with:
          submodules: true
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
        with:
          python-version: 3.12

      - name: ci/Install dependencies
        run: make python-deps

      - name: ci/Run tests
        env:
          TZ: UTC
        run: make test

      - name: ci/Build docs
        env:
          TZ: UTC
        run: make html

      - name: ci/Persist docs artifacts
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882  # v4.4.3
        with:
          name: docs
          path: build/html

      - name: ci/Persist doc logs artifacts
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882  # v4.4.3
        with:
          name: doc-logs
          path: build/*.log
