name: preview-env-setup-template

on:
  workflow_call:
    inputs:
      PR_NUMBER:
        type: string
        required: true
      TRIGGERING_ACTOR:
        type: string
        required: true
      COMMIT_SHA:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          submodules: true
          fetch-depth: 0
          ref: ${{ inputs.COMMIT_SHA }}

      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Build
        run: make SPHINXOPTS="-j auto -D html_baseurl=http://mattermost-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/${{ inputs.PR_NUMBER }}" html

      - uses: shallwefootball/s3-upload-action@4350529f410221787ccf424e50133cbc1b52704e # v1.3.3
        name: Upload Preview Env
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: ./build/html
          destination_dir: ${{ inputs.PR_NUMBER }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with: 
          files: '**/*.rst'

      - name: Split file names
        id: split-file-names
        run: |
          file_count=$(echo "${{ steps.changed-files.outputs.all_changed_and_modified_files }}" | wc -w)
          echo "file_count=$file_count" >> $GITHUB_OUTPUT

      - name: Extract path
        id: extract-path
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_and_modified_files }}"
          processed_files=""
          for file in ${changed_files}; do
            file_paths=$(echo "$file" | sed 's|^[^/]*/||; s|\.[^.]*$||')
            processed_files+="$file_paths "
          done
          if [ "${{ steps.split-file-names.outputs.file_count }}" -le 10 ]; then
            echo "file_paths=$processed_files" >> $GITHUB_OUTPUT
          fi

      - name: Add comment to PR
        uses: peter-evans/create-or-update-comment@7dfe4b0aa0c4bbd06d172692ff8a9e18381d6979 # v3.0.1
        env: 
          file_paths: ${{ steps.extract-path.outputs.file_paths }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ inputs.PR_NUMBER }}
          body: |
            Newest code from ${{ inputs.TRIGGERING_ACTOR }} has been published to [preview environment](http://mattermost-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/${{ inputs.PR_NUMBER }}) for Git SHA ${{ inputs.COMMIT_SHA }}
            Links: ${{ env.file_paths }}
